name: async_redux_core
description: Dart-only core package for the Async Redux state management, the easy and powerful version of Redux.
version: 1.3.1
# author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/async_redux_core
topics:
  - redux
  - state-management
  - reactive-programming

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  i18n_extension_core: ^5.0.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
